// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents the execution status
type Status int32

const (
	Status_STATUS_UNSPECIFIED           Status = 0
	Status_STATUS_OK                    Status = 1
	Status_STATUS_RUNTIME_ERROR         Status = 2
	Status_STATUS_TIME_LIMIT_EXCEEDED   Status = 3
	Status_STATUS_MEMORY_LIMIT_EXCEEDED Status = 4
	Status_STATUS_OUTPUT_LIMIT_EXCEEDED Status = 5
	Status_STATUS_TERMINATED            Status = 6
	Status_STATUS_UNKNOWN               Status = 7
	Status_STATUS_SKIPPED               Status = 8
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_RUNTIME_ERROR",
		3: "STATUS_TIME_LIMIT_EXCEEDED",
		4: "STATUS_MEMORY_LIMIT_EXCEEDED",
		5: "STATUS_OUTPUT_LIMIT_EXCEEDED",
		6: "STATUS_TERMINATED",
		7: "STATUS_UNKNOWN",
		8: "STATUS_SKIPPED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":           0,
		"STATUS_OK":                    1,
		"STATUS_RUNTIME_ERROR":         2,
		"STATUS_TIME_LIMIT_EXCEEDED":   3,
		"STATUS_MEMORY_LIMIT_EXCEEDED": 4,
		"STATUS_OUTPUT_LIMIT_EXCEEDED": 5,
		"STATUS_TERMINATED":            6,
		"STATUS_UNKNOWN":               7,
		"STATUS_SKIPPED":               8,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// File represents a file to be created in the sandbox
type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Process represents a single execution step
type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Cmd           []string               `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty"`
	Stdin         string                 `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	MemoryLimitMb int64                  `protobuf:"varint,4,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`
	TimeLimitMs   uint64                 `protobuf:"varint,5,opt,name=time_limit_ms,json=timeLimitMs,proto3" json:"time_limit_ms,omitempty"`
	ProcLimit     int64                  `protobuf:"varint,6,opt,name=proc_limit,json=procLimit,proto3" json:"proc_limit,omitempty"`
	Files         []string               `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty"`
	Persist       []string               `protobuf:"bytes,8,rep,name=persist,proto3" json:"persist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Process) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Process) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Process) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

func (x *Process) GetMemoryLimitMb() int64 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

func (x *Process) GetTimeLimitMs() uint64 {
	if x != nil {
		return x.TimeLimitMs
	}
	return 0
}

func (x *Process) GetProcLimit() int64 {
	if x != nil {
		return x.ProcLimit
	}
	return 0
}

func (x *Process) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Process) GetPersist() []string {
	if x != nil {
		return x.Persist
	}
	return nil
}

// Report contains the execution results
type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=castletown.Status" json:"status,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Signal        int32                  `protobuf:"varint,3,opt,name=signal,proto3" json:"signal,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	CpuTime       uint64                 `protobuf:"varint,6,opt,name=cpu_time,json=cpuTime,proto3" json:"cpu_time,omitempty"`
	Memory        uint64                 `protobuf:"varint,7,opt,name=memory,proto3" json:"memory,omitempty"`
	WallTime      int64                  `protobuf:"varint,8,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	StartAt       int64                  `protobuf:"varint,9,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`     // Unix timestamp in nanoseconds
	FinishAt      int64                  `protobuf:"varint,10,opt,name=finish_at,json=finishAt,proto3" json:"finish_at,omitempty"` // Unix timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Report) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Report) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Report) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

func (x *Report) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *Report) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *Report) GetCpuTime() uint64 {
	if x != nil {
		return x.CpuTime
	}
	return 0
}

func (x *Report) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Report) GetWallTime() int64 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *Report) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *Report) GetFinishAt() int64 {
	if x != nil {
		return x.FinishAt
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\n" +
	"castletown\"4\n" +
	"\x04File\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xe2\x01\n" +
	"\aProcess\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x10\n" +
	"\x03cmd\x18\x02 \x03(\tR\x03cmd\x12\x14\n" +
	"\x05stdin\x18\x03 \x01(\tR\x05stdin\x12&\n" +
	"\x0fmemory_limit_mb\x18\x04 \x01(\x03R\rmemoryLimitMb\x12\"\n" +
	"\rtime_limit_ms\x18\x05 \x01(\x04R\vtimeLimitMs\x12\x1d\n" +
	"\n" +
	"proc_limit\x18\x06 \x01(\x03R\tprocLimit\x12\x14\n" +
	"\x05files\x18\a \x03(\tR\x05files\x12\x18\n" +
	"\apersist\x18\b \x03(\tR\apersist\"\xa1\x02\n" +
	"\x06Report\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.castletown.StatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\x05R\x06signal\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x19\n" +
	"\bcpu_time\x18\x06 \x01(\x04R\acpuTime\x12\x16\n" +
	"\x06memory\x18\a \x01(\x04R\x06memory\x12\x1b\n" +
	"\twall_time\x18\b \x01(\x03R\bwallTime\x12\x19\n" +
	"\bstart_at\x18\t \x01(\x03R\astartAt\x12\x1b\n" +
	"\tfinish_at\x18\n" +
	" \x01(\x03R\bfinishAt*\xec\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x18\n" +
	"\x14STATUS_RUNTIME_ERROR\x10\x02\x12\x1e\n" +
	"\x1aSTATUS_TIME_LIMIT_EXCEEDED\x10\x03\x12 \n" +
	"\x1cSTATUS_MEMORY_LIMIT_EXCEEDED\x10\x04\x12 \n" +
	"\x1cSTATUS_OUTPUT_LIMIT_EXCEEDED\x10\x05\x12\x15\n" +
	"\x11STATUS_TERMINATED\x10\x06\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\a\x12\x12\n" +
	"\x0eSTATUS_SKIPPED\x10\bB%Z#github.com/joshjms/castletown/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []any{
	(Status)(0),     // 0: castletown.Status
	(*File)(nil),    // 1: castletown.File
	(*Process)(nil), // 2: castletown.Process
	(*Report)(nil),  // 3: castletown.Report
}
var file_common_proto_depIdxs = []int32{
	0, // 0: castletown.Report.status:type_name -> castletown.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
