// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: done.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DoneService_Done_FullMethodName = "/castletown.DoneService/Done"
)

// DoneServiceClient is the client API for DoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DoneService handles job completion notifications
type DoneServiceClient interface {
	Done(ctx context.Context, in *DoneRequest, opts ...grpc.CallOption) (*DoneResponse, error)
}

type doneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDoneServiceClient(cc grpc.ClientConnInterface) DoneServiceClient {
	return &doneServiceClient{cc}
}

func (c *doneServiceClient) Done(ctx context.Context, in *DoneRequest, opts ...grpc.CallOption) (*DoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoneResponse)
	err := c.cc.Invoke(ctx, DoneService_Done_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoneServiceServer is the server API for DoneService service.
// All implementations must embed UnimplementedDoneServiceServer
// for forward compatibility.
//
// DoneService handles job completion notifications
type DoneServiceServer interface {
	Done(context.Context, *DoneRequest) (*DoneResponse, error)
	mustEmbedUnimplementedDoneServiceServer()
}

// UnimplementedDoneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoneServiceServer struct{}

func (UnimplementedDoneServiceServer) Done(context.Context, *DoneRequest) (*DoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Done not implemented")
}
func (UnimplementedDoneServiceServer) mustEmbedUnimplementedDoneServiceServer() {}
func (UnimplementedDoneServiceServer) testEmbeddedByValue()                     {}

// UnsafeDoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoneServiceServer will
// result in compilation errors.
type UnsafeDoneServiceServer interface {
	mustEmbedUnimplementedDoneServiceServer()
}

func RegisterDoneServiceServer(s grpc.ServiceRegistrar, srv DoneServiceServer) {
	// If the following call pancis, it indicates UnimplementedDoneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DoneService_ServiceDesc, srv)
}

func _DoneService_Done_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoneServiceServer).Done(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoneService_Done_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoneServiceServer).Done(ctx, req.(*DoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoneService_ServiceDesc is the grpc.ServiceDesc for DoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "castletown.DoneService",
	HandlerType: (*DoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Done",
			Handler:    _DoneService_Done_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "done.proto",
}
