// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: done.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DoneRequest contains the job ID to mark as done
type DoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneRequest) Reset() {
	*x = DoneRequest{}
	mi := &file_done_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneRequest) ProtoMessage() {}

func (x *DoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_done_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneRequest.ProtoReflect.Descriptor instead.
func (*DoneRequest) Descriptor() ([]byte, []int) {
	return file_done_proto_rawDescGZIP(), []int{0}
}

func (x *DoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DoneResponse is an empty response
type DoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneResponse) Reset() {
	*x = DoneResponse{}
	mi := &file_done_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneResponse) ProtoMessage() {}

func (x *DoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_done_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneResponse.ProtoReflect.Descriptor instead.
func (*DoneResponse) Descriptor() ([]byte, []int) {
	return file_done_proto_rawDescGZIP(), []int{1}
}

var File_done_proto protoreflect.FileDescriptor

const file_done_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"done.proto\x12\n" +
	"castletown\"\x1d\n" +
	"\vDoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x0e\n" +
	"\fDoneResponse2H\n" +
	"\vDoneService\x129\n" +
	"\x04Done\x12\x17.castletown.DoneRequest\x1a\x18.castletown.DoneResponseB%Z#github.com/joshjms/castletown/protob\x06proto3"

var (
	file_done_proto_rawDescOnce sync.Once
	file_done_proto_rawDescData []byte
)

func file_done_proto_rawDescGZIP() []byte {
	file_done_proto_rawDescOnce.Do(func() {
		file_done_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_done_proto_rawDesc), len(file_done_proto_rawDesc)))
	})
	return file_done_proto_rawDescData
}

var file_done_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_done_proto_goTypes = []any{
	(*DoneRequest)(nil),  // 0: castletown.DoneRequest
	(*DoneResponse)(nil), // 1: castletown.DoneResponse
}
var file_done_proto_depIdxs = []int32{
	0, // 0: castletown.DoneService.Done:input_type -> castletown.DoneRequest
	1, // 1: castletown.DoneService.Done:output_type -> castletown.DoneResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_done_proto_init() }
func file_done_proto_init() {
	if File_done_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_done_proto_rawDesc), len(file_done_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_done_proto_goTypes,
		DependencyIndexes: file_done_proto_depIdxs,
		MessageInfos:      file_done_proto_msgTypes,
	}.Build()
	File_done_proto = out.File
	file_done_proto_goTypes = nil
	file_done_proto_depIdxs = nil
}
