// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: exec.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecRequest contains the job execution parameters
type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Files         []*File                `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Procs         []*Process             `protobuf:"bytes,3,rep,name=procs,proto3" json:"procs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ExecRequest) GetProcs() []*Process {
	if x != nil {
		return x.Procs
	}
	return nil
}

// ExecResponse contains the execution results
type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reports       []*Report              `protobuf:"bytes,2,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecResponse) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

var File_exec_proto protoreflect.FileDescriptor

const file_exec_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"exec.proto\x12\n" +
	"castletown\x1a\fcommon.proto\"p\n" +
	"\vExecRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x05files\x18\x02 \x03(\v2\x10.castletown.FileR\x05files\x12)\n" +
	"\x05procs\x18\x03 \x03(\v2\x13.castletown.ProcessR\x05procs\"L\n" +
	"\fExecResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\areports\x18\x02 \x03(\v2\x12.castletown.ReportR\areports2K\n" +
	"\vExecService\x12<\n" +
	"\aExecute\x12\x17.castletown.ExecRequest\x1a\x18.castletown.ExecResponseB%Z#github.com/joshjms/castletown/protob\x06proto3"

var (
	file_exec_proto_rawDescOnce sync.Once
	file_exec_proto_rawDescData []byte
)

func file_exec_proto_rawDescGZIP() []byte {
	file_exec_proto_rawDescOnce.Do(func() {
		file_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)))
	})
	return file_exec_proto_rawDescData
}

var file_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exec_proto_goTypes = []any{
	(*ExecRequest)(nil),  // 0: castletown.ExecRequest
	(*ExecResponse)(nil), // 1: castletown.ExecResponse
	(*File)(nil),         // 2: castletown.File
	(*Process)(nil),      // 3: castletown.Process
	(*Report)(nil),       // 4: castletown.Report
}
var file_exec_proto_depIdxs = []int32{
	2, // 0: castletown.ExecRequest.files:type_name -> castletown.File
	3, // 1: castletown.ExecRequest.procs:type_name -> castletown.Process
	4, // 2: castletown.ExecResponse.reports:type_name -> castletown.Report
	0, // 3: castletown.ExecService.Execute:input_type -> castletown.ExecRequest
	1, // 4: castletown.ExecService.Execute:output_type -> castletown.ExecResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_exec_proto_init() }
func file_exec_proto_init() {
	if File_exec_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exec_proto_goTypes,
		DependencyIndexes: file_exec_proto_depIdxs,
		MessageInfos:      file_exec_proto_msgTypes,
	}.Build()
	File_exec_proto = out.File
	file_exec_proto_goTypes = nil
	file_exec_proto_depIdxs = nil
}
