name: Test E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-sandbox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

          sudo apt install -y skopeo
          
          sudo apt install -y curl tar
          curl -L https://github.com/opencontainers/umoci/releases/download/v0.5.1/umoci.linux.amd64 -o umoci
          chmod +x umoci
          sudo mv umoci /usr/local/bin/umoci

          wget https://go.dev/dl/go1.25.1.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.25.1.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go version

      - name: Run e2e tests
        run: make test-e2e
